# Generated by Django 6.0.1 on 2026-01-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('equipamiento', 'Equipamiento'), ('mantenimiento', 'Mantenimiento'), ('reparaciones', 'Reparaciones'), ('insumos', 'Insumos de Limpieza'), ('marketing', 'Marketing/Publicidad'), ('suplementos', 'Suplementos/Productos'), ('servicios_profesionales', 'Servicios Profesionales'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito')], max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('comprobante', models.CharField(blank=True, help_text='Nº de factura/recibo', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('alquiler', 'Alquiler'), ('servicios', 'Servicios (luz, agua, gas)'), ('internet', 'Internet/Teléfono'), ('salarios', 'Salarios'), ('impuestos', 'Impuestos'), ('seguro', 'Seguros'), ('limpieza', 'Limpieza'), ('otro', 'Otro')], max_length=20)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimiento', models.IntegerField(help_text='Día del mes que vence (1-31)')),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto Fijo',
                'verbose_name_plural': 'Gastos Fijos',
                'ordering': ['dia_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_pago', models.DateField(blank=True, null=True)),
                ('proximo_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('al_dia', 'Al Día'), ('debe', 'Debe'), ('suspendido', 'Suspendido por Falta de Pago')], default='al_dia', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cuenta', to='clientes.cliente')),
                ('membresia_activa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_cuenta', to='membresias.membresia')),
            ],
            options={
                'verbose_name': 'Estado de Cuenta',
                'verbose_name_plural': 'Estados de Cuenta',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('mercadopago', 'Mercado Pago')], max_length=20)),
                ('concepto', models.CharField(choices=[('membresia', 'Membresía'), ('inscripcion', 'Inscripción'), ('clase_particular', 'Clase Particular'), ('producto', 'Venta de Producto'), ('otro', 'Otro')], default='membresia', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='clientes.cliente')),
                ('membresia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='membresias.membresia')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
