# Generated by Django 6.0.1 on 2026-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='categoria',
            field=models.CharField(choices=[('gastos_fijos', 'Gastos Fijos'), ('equipamiento', 'Equipamiento'), ('mantenimiento', 'Mantenimiento'), ('reparaciones', 'Reparaciones'), ('insumos', 'Insumos de Limpieza'), ('marketing', 'Marketing/Publicidad'), ('suplementos', 'Suplementos/Productos'), ('servicios_profesionales', 'Servicios Profesionales'), ('otro', 'Otro')], max_length=30),
        ),
    ]
