# Generated by Django 6.0.1 on 2026-01-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('nombre', models.CharField(help_text='Ej: Día de Piernas, Upper Body, etc.', max_length=100)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Día de Entrenamiento',
                'verbose_name_plural': 'Días de Entrenamiento',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('fuerza', 'Fuerza'), ('cardio', 'Cardio'), ('flexibilidad', 'Flexibilidad'), ('funcional', 'Funcional'), ('olimpico', 'Olímpico')], max_length=20)),
                ('grupo_muscular', models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('core', 'Core'), ('full_body', 'Cuerpo Completo')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Plan 2x Semana, Plan Premium', max_length=100)),
                ('frecuencia_semanal', models.IntegerField(help_text='Veces que puede asistir por semana (2, 3, 5)')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio mensual actual', max_digits=10)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del plan')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['frecuencia_semanal'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(help_text='Orden de ejecución en el día')),
                ('series', models.IntegerField(default=3)),
                ('repeticiones', models.CharField(help_text='Ej: 10, 8-12, MAX, etc.', max_length=50)),
                ('descanso', models.CharField(blank=True, help_text='Ej: 60s, 1-2min, etc.', max_length=50)),
                ('tipo_serie', models.CharField(choices=[('normal', 'Normal'), ('superset', 'Superset'), ('dropset', 'Dropset'), ('amrap', 'AMRAP'), ('emom', 'EMOM'), ('for_time', 'For Time')], default='normal', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Instrucciones específicas para este ejercicio')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='membresias.diaentrenamiento')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='membresias.ejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicio del Día',
                'verbose_name_plural': 'Ejercicios del Día',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_contratado', models.DecimalField(decimal_places=2, help_text='Precio al momento de contratar (puede diferir del precio actual del plan)', max_digits=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='activa', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='clientes.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='membresias.plan')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('objetivo', models.TextField(help_text='Objetivo del plan (ej: pérdida de peso, ganancia muscular, etc.)')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(help_text='Automáticamente 4 semanas después del inicio')),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número de semana (1-4)')),
                ('notas', models.TextField(blank=True, help_text='Notas específicas para esta semana')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='membresias.rutina')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('rutina', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='diaentrenamiento',
            name='semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='membresias.semana'),
        ),
        migrations.AlterUniqueTogether(
            name='diaentrenamiento',
            unique_together={('semana', 'dia_semana')},
        ),
    ]
