# Generated by Django 6.0.1 on 2026-02-21 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_ingresado', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('permitido', 'Permitido'), ('denegado', 'Denegado')], max_length=20)),
                ('motivo_denegacion', models.CharField(blank=True, choices=[('no_encontrado', 'DNI no encontrado'), ('cliente_inactivo', 'Cliente inactivo'), ('sin_membresia', 'Sin membresía activa'), ('membresia_vencida', 'Membresía vencida')], max_length=30, null=True)),
                ('dias_restantes', models.IntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='clientes.cliente')),
                ('membresia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='membresias.membresia')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
